name: Rust

on:
  push:
    branches: [ main.py ]
  pull_request:
    branches: [ main.py ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build @params
    - name: Run tests
      run: cargo test @params
